######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : rack-resiliency-1x-20260125-093729, Index = 0, Count = null
# SUBMIT FILE NAME : register_local_1_0.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 KUBECONFIG=/home/snu/kubernetes/kubeconfig-master PATH=/home/snu/pegasus-venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=649c3888-0a42-4850-bdf5-2ed612b5134f PEGASUS_WF_LABEL=rack-resiliency-1x-20260125-093729 PEGASUS_DAG_JOB_ID=register_local_1_0 PEGASUS_SITE=local PEGASUS_BIN_DIR=/usr/bin"
arguments = "pegasus-kickstart  -n pegasus::rc-client -N null -R local  -L rack-resiliency-1x-20260125-093729 -T 2026-01-25T09:37:29+05:30 /usr/bin/pegasus-rc-client --prefix pegasus.catalog.replica.output --conf /home/snu/kubernetes/comparison-logs/pegasus-1x/pegasus-1x-20260125-093729-1/submit/snu/pegasus/rack-resiliency-1x-20260125-093729/run0001/pegasus.4771673394105424979.properties -v --meta /home/snu/kubernetes/comparison-logs/pegasus-1x/pegasus-1x-20260125-093729-1/submit/snu/pegasus/rack-resiliency-1x-20260125-093729/run0001/00/00/node-failure-sim_ID0000004.meta --insert /home/snu/kubernetes/comparison-logs/pegasus-1x/pegasus-1x-20260125-093729-1/submit/snu/pegasus/rack-resiliency-1x-20260125-093729/run0001/00/00/register_local_1_0.in"
error = /home/snu/kubernetes/comparison-logs/pegasus-1x/pegasus-1x-20260125-093729-1/submit/snu/pegasus/rack-resiliency-1x-20260125-093729/run0001//00/00/register_local_1_0.err
executable = /usr/share/pegasus/sh/pegasus-lite-local.sh
log = /home/snu/kubernetes/comparison-logs/pegasus-1x/pegasus-1x-20260125-093729-1/submit/snu/pegasus/rack-resiliency-1x-20260125-093729/run0001/rack-resiliency-1x-20260125-093729-0.log
notification = NEVER
output = /home/snu/kubernetes/comparison-logs/pegasus-1x/pegasus-1x-20260125-093729-1/submit/snu/pegasus/rack-resiliency-1x-20260125-093729/run0001//00/00/register_local_1_0.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 50
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "649c3888-0a42-4850-bdf5-2ed612b5134f"
+pegasus_wf_uuid = "649c3888-0a42-4850-bdf5-2ed612b5134f"
+pegasus_version = "5.0.9"
+pegasus_wf_name = "rack-resiliency-1x-20260125-093729-0"
+pegasus_wf_time = "20260125T093729+0530"
+pegasus_wf_xformation = "pegasus::rc-client"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "register_local_1_0"
+pegasus_job_class = 4
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_gpus = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
