x-pegasus:
  apiLang: python
  createdBy: pegasus
  createdOn: 02-12-26T20:39:51Z
pegasus: 5.0.4
name: montage-1.0deg-20260212-203951
jobs:
- type: job
  namespace: montage
  version: '6.0'
  name: mProjectPP
  id: ID0000001
  arguments:
  - -X
  - input_001.fits
  - projected_001.fits
  uses:
  - lfn: input_001.fits
    type: input
  - lfn: projected_001.fits
    type: output
    stageOut: false
    registerReplica: true
  profiles:
    pegasus:
      label: project-1
- type: job
  namespace: montage
  version: '6.0'
  name: mProjectPP
  id: ID0000002
  arguments:
  - -X
  - input_002.fits
  - projected_002.fits
  uses:
  - lfn: input_002.fits
    type: input
  - lfn: projected_002.fits
    type: output
    stageOut: false
    registerReplica: true
  profiles:
    pegasus:
      label: project-2
- type: job
  namespace: montage
  version: '6.0'
  name: mProjectPP
  id: ID0000003
  arguments:
  - -X
  - input_003.fits
  - projected_003.fits
  uses:
  - lfn: projected_003.fits
    type: output
    stageOut: false
    registerReplica: true
  - lfn: input_003.fits
    type: input
  profiles:
    pegasus:
      label: project-3
- type: job
  namespace: montage
  version: '6.0'
  name: mProjectPP
  id: ID0000004
  arguments:
  - -X
  - input_004.fits
  - projected_004.fits
  uses:
  - lfn: projected_004.fits
    type: output
    stageOut: false
    registerReplica: true
  - lfn: input_004.fits
    type: input
  profiles:
    pegasus:
      label: project-4
- type: job
  namespace: montage
  version: '6.0'
  name: mImgtbl
  id: ID0000005
  arguments:
  - -t
  - '4'
  - images.tbl
  uses:
  - lfn: projected_003.fits
    type: input
  - lfn: projected_001.fits
    type: input
  - lfn: projected_004.fits
    type: input
  - lfn: images.tbl
    type: output
    stageOut: false
    registerReplica: true
  - lfn: projected_002.fits
    type: input
- type: job
  namespace: montage
  version: '6.0'
  name: mDiffFit
  id: ID0000006
  arguments:
  - projected_001.fits
  - projected_002.fits
  - diff_001.fits
  - fit_001.txt
  uses:
  - lfn: fit_001.txt
    type: output
    stageOut: false
    registerReplica: true
  - lfn: projected_001.fits
    type: input
  - lfn: projected_002.fits
    type: input
  - lfn: diff_001.fits
    type: output
    stageOut: false
    registerReplica: true
- type: job
  namespace: montage
  version: '6.0'
  name: mDiffFit
  id: ID0000007
  arguments:
  - projected_002.fits
  - projected_003.fits
  - diff_002.fits
  - fit_002.txt
  uses:
  - lfn: projected_003.fits
    type: input
  - lfn: diff_002.fits
    type: output
    stageOut: false
    registerReplica: true
  - lfn: projected_002.fits
    type: input
  - lfn: fit_002.txt
    type: output
    stageOut: false
    registerReplica: true
- type: job
  namespace: montage
  version: '6.0'
  name: mDiffFit
  id: ID0000008
  arguments:
  - projected_003.fits
  - projected_004.fits
  - diff_003.fits
  - fit_003.txt
  uses:
  - lfn: projected_003.fits
    type: input
  - lfn: fit_003.txt
    type: output
    stageOut: false
    registerReplica: true
  - lfn: projected_004.fits
    type: input
  - lfn: diff_003.fits
    type: output
    stageOut: false
    registerReplica: true
- type: job
  namespace: montage
  version: '6.0'
  name: mConcatFit
  id: ID0000009
  arguments:
  - -o
  - fits.tbl
  uses:
  - lfn: fit_001.txt
    type: input
  - lfn: fit_003.txt
    type: input
  - lfn: fit_002.txt
    type: input
  - lfn: fits.tbl
    type: output
    stageOut: false
    registerReplica: true
- type: job
  namespace: montage
  version: '6.0'
  name: mBgModel
  id: ID0000010
  arguments:
  - images.tbl
  - fits.tbl
  - corrections.tbl
  uses:
  - lfn: corrections.tbl
    type: output
    stageOut: false
    registerReplica: true
  - lfn: images.tbl
    type: input
  - lfn: fits.tbl
    type: input
- type: job
  namespace: montage
  version: '6.0'
  name: mBgExec
  id: ID0000011
  arguments:
  - projected_001.fits
  - corrections.tbl
  - corrected_001.fits
  uses:
  - lfn: projected_001.fits
    type: input
  - lfn: corrected_001.fits
    type: output
    stageOut: false
    registerReplica: true
  - lfn: corrections.tbl
    type: input
- type: job
  namespace: montage
  version: '6.0'
  name: mBgExec
  id: ID0000012
  arguments:
  - projected_002.fits
  - corrections.tbl
  - corrected_002.fits
  uses:
  - lfn: corrected_002.fits
    type: output
    stageOut: false
    registerReplica: true
  - lfn: projected_002.fits
    type: input
  - lfn: corrections.tbl
    type: input
- type: job
  namespace: montage
  version: '6.0'
  name: mBgExec
  id: ID0000013
  arguments:
  - projected_003.fits
  - corrections.tbl
  - corrected_003.fits
  uses:
  - lfn: projected_003.fits
    type: input
  - lfn: corrected_003.fits
    type: output
    stageOut: false
    registerReplica: true
  - lfn: corrections.tbl
    type: input
- type: job
  namespace: montage
  version: '6.0'
  name: mBgExec
  id: ID0000014
  arguments:
  - projected_004.fits
  - corrections.tbl
  - corrected_004.fits
  uses:
  - lfn: corrected_004.fits
    type: output
    stageOut: false
    registerReplica: true
  - lfn: projected_004.fits
    type: input
  - lfn: corrections.tbl
    type: input
- type: job
  namespace: montage
  version: '6.0'
  name: mAdd
  id: ID0000015
  arguments:
  - -o
  - mosaic.fits
  uses:
  - lfn: corrected_003.fits
    type: input
  - lfn: corrected_004.fits
    type: input
  - lfn: mosaic.fits
    type: output
    stageOut: true
    registerReplica: true
  - lfn: corrected_002.fits
    type: input
  - lfn: corrected_001.fits
    type: input
- type: job
  namespace: montage
  version: '6.0'
  name: mShrink
  id: ID0000016
  arguments:
  - mosaic.fits
  - mosaic_thumb.fits
  - '0.1'
  uses:
  - lfn: mosaic.fits
    type: input
  - lfn: mosaic_thumb.fits
    type: output
    stageOut: true
    registerReplica: true
- type: job
  namespace: montage
  version: '6.0'
  name: mJPEG
  id: ID0000017
  arguments:
  - mosaic.fits
  - mosaic.jpg
  uses:
  - lfn: mosaic.fits
    type: input
  - lfn: mosaic.jpg
    type: output
    stageOut: true
    registerReplica: true
jobDependencies:
- id: ID0000001
  children:
  - ID0000005
  - ID0000006
  - ID0000011
- id: ID0000002
  children:
  - ID0000005
  - ID0000006
  - ID0000007
  - ID0000012
- id: ID0000003
  children:
  - ID0000005
  - ID0000007
  - ID0000008
  - ID0000013
- id: ID0000004
  children:
  - ID0000005
  - ID0000008
  - ID0000014
- id: ID0000005
  children:
  - ID0000007
  - ID0000006
  - ID0000008
  - ID0000010
- id: ID0000006
  children:
  - ID0000009
- id: ID0000007
  children:
  - ID0000009
- id: ID0000008
  children:
  - ID0000009
- id: ID0000009
  children:
  - ID0000010
- id: ID0000010
  children:
  - ID0000013
  - ID0000014
  - ID0000012
  - ID0000011
- id: ID0000011
  children:
  - ID0000015
- id: ID0000012
  children:
  - ID0000015
- id: ID0000013
  children:
  - ID0000015
- id: ID0000014
  children:
  - ID0000015
- id: ID0000015
  children:
  - ID0000017
  - ID0000016
