<?xml version="1.0" encoding="UTF-8"?>
<adag xmlns="http://pegasus.isi.edu/schema/DAX" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pegasus.isi.edu/schema/DAX http://pegasus.isi.edu/schema/dax-3.6.xsd" version="3.6" name="test-workflow">
  <job id="ID0000001" name="health-check" namespace="rack" version="1.0">
    <argument>health-check --stabilization-time=2</argument>
    <stdout name="out1.txt" link="output"/>
    <uses name="out1.txt" link="output" register="false" transfer="true"/>
  </job>
</adag>
