######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : rack-resiliency-1x-20260122-101553, Index = 0, Count = null
# SUBMIT FILE NAME : stage_out_local_local_4_0.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 KUBECONFIG=/home/snu/kubernetes/kubeconfig-master PATH=/home/snu/pegasus-venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=68bd0e78-a2e7-4b68-81c6-2989c1e10aec PEGASUS_WF_LABEL=rack-resiliency-1x-20260122-101553 PEGASUS_DAG_JOB_ID=stage_out_local_local_4_0 PEGASUS_SITE=local _PEGASUS_TRANSFER_INPUT_FILES=/home/snu/kubernetes/comparison-logs/pegasus-1x/pegasus-1x-20260122-101553-1/submit/snu/pegasus/rack-resiliency-1x-20260122-101553/run0001/00/00/health-check_ID0000007.meta, PEGASUS_BIN_DIR=/usr/bin _PEGASUS_CONNECT_STDIN=true"
arguments = "pegasus-kickstart  -n pegasus::transfer -N null -i - -R local  -L rack-resiliency-1x-20260122-101553 -T 2026-01-22T10:15:53+05:30 pegasus-transfer  --threads 2 "
error = /home/snu/kubernetes/comparison-logs/pegasus-1x/pegasus-1x-20260122-101553-1/submit/snu/pegasus/rack-resiliency-1x-20260122-101553/run0001//00/00/stage_out_local_local_4_0.err
executable = /usr/share/pegasus/sh/pegasus-lite-local.sh
input = /home/snu/kubernetes/comparison-logs/pegasus-1x/pegasus-1x-20260122-101553-1/submit/snu/pegasus/rack-resiliency-1x-20260122-101553/run0001//00/00/stage_out_local_local_4_0.in
log = /home/snu/kubernetes/comparison-logs/pegasus-1x/pegasus-1x-20260122-101553-1/submit/snu/pegasus/rack-resiliency-1x-20260122-101553/run0001/rack-resiliency-1x-20260122-101553-0.log
notification = NEVER
output = /home/snu/kubernetes/comparison-logs/pegasus-1x/pegasus-1x-20260122-101553-1/submit/snu/pegasus/rack-resiliency-1x-20260122-101553/run0001//00/00/stage_out_local_local_4_0.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 900
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "68bd0e78-a2e7-4b68-81c6-2989c1e10aec"
+pegasus_wf_uuid = "68bd0e78-a2e7-4b68-81c6-2989c1e10aec"
+pegasus_version = "5.0.9"
+pegasus_wf_name = "rack-resiliency-1x-20260122-101553-0"
+pegasus_wf_time = "20260122T101553+0530"
+pegasus_wf_xformation = "pegasus::transfer"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "stage_out_local_local_4_0"
+pegasus_job_class = 3
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_gpus = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
