name: Scaled (2x) Rack Resiliency Simulation

on:
  workflow_dispatch:
    inputs:
      stabilization_time_node:
        description: 'Stabilization time after node failure (seconds)'
        required: false
        default: '60'
      stabilization_time_rack:
        description: 'Stabilization time after rack failure (seconds)'
        required: false
        default: '60'

env:
  LOG_BASE_PATH: /home/snu/kubernetes/comparison-logs/github-actions-scaled
  SCALE: '2x'

jobs:
  # ==========================================================================
  # INITIALIZE
  # ==========================================================================
  initialize:
    name: Initialize Scaled Run
    runs-on: self-hosted
    outputs:
      run_id: ${{ steps.init.outputs.run_id }}
      local_log_dir: ${{ steps.init.outputs.local_log_dir }}
    steps:
      - name: Configure kubectl
        run: |
          for path in ~/.kube/config /home/snu/.kube/config /home/snu/kubernetes/kubeconfig-master; do
            if [ -f "$path" ]; then
              export KUBECONFIG="$path"
              break
            fi
          done
          kubectl get nodes

      - name: Initialize Run
        id: init
        run: |
          RUN_ID="scaled-gha-$(date +%Y%m%d-%H%M%S)-${GITHUB_RUN_ID}"
          LOCAL_LOG_DIR="${LOG_BASE_PATH}/${RUN_ID}"
          mkdir -p "${LOCAL_LOG_DIR}"
          
          echo "run_id=${RUN_ID}" >> $GITHUB_OUTPUT
          echo "local_log_dir=${LOCAL_LOG_DIR}" >> $GITHUB_OUTPUT
          
          echo "================================================================"
          echo "SCALED (2x) GITHUB ACTIONS WORKFLOW"
          echo "Scale: 6 HC, 2 Node Sim, 2 Interim HC, 2 Rack Sim, 2 Final HC"
          echo "================================================================"
          echo "Run ID: ${RUN_ID}"

  # ==========================================================================
  # PHASE 1: 6 PARALLEL HEALTH CHECKS
  # ==========================================================================
  health-check-1:
    name: Health Check 1/6
    needs: [initialize]
    runs-on: self-hosted
    steps:
      - name: Run Health Check
        run: |
          START=$(date +%s)
          kubectl get nodes -o wide
          END=$(date +%s)
          echo "HEALTH_CHECK_1,${START},${END},$((END-START)),SUCCESS" >> "${{ needs.initialize.outputs.local_log_dir }}/timing.csv"

  health-check-2:
    name: Health Check 2/6
    needs: [initialize]
    runs-on: self-hosted
    steps:
      - name: Run Health Check
        run: |
          START=$(date +%s)
          kubectl get nodes -o wide
          END=$(date +%s)
          echo "HEALTH_CHECK_2,${START},${END},$((END-START)),SUCCESS" >> "${{ needs.initialize.outputs.local_log_dir }}/timing.csv"

  health-check-3:
    name: Health Check 3/6
    needs: [initialize]
    runs-on: self-hosted
    steps:
      - name: Run Health Check
        run: |
          START=$(date +%s)
          kubectl get nodes -o wide
          END=$(date +%s)
          echo "HEALTH_CHECK_3,${START},${END},$((END-START)),SUCCESS" >> "${{ needs.initialize.outputs.local_log_dir }}/timing.csv"

  health-check-4:
    name: Health Check 4/6
    needs: [initialize]
    runs-on: self-hosted
    steps:
      - name: Run Health Check
        run: |
          START=$(date +%s)
          kubectl get nodes -o wide
          END=$(date +%s)
          echo "HEALTH_CHECK_4,${START},${END},$((END-START)),SUCCESS" >> "${{ needs.initialize.outputs.local_log_dir }}/timing.csv"

  health-check-5:
    name: Health Check 5/6
    needs: [initialize]
    runs-on: self-hosted
    steps:
      - name: Run Health Check
        run: |
          START=$(date +%s)
          kubectl get nodes -o wide
          END=$(date +%s)
          echo "HEALTH_CHECK_5,${START},${END},$((END-START)),SUCCESS" >> "${{ needs.initialize.outputs.local_log_dir }}/timing.csv"

  health-check-6:
    name: Health Check 6/6
    needs: [initialize]
    runs-on: self-hosted
    steps:
      - name: Run Health Check
        run: |
          START=$(date +%s)
          kubectl get nodes -o wide
          END=$(date +%s)
          echo "HEALTH_CHECK_6,${START},${END},$((END-START)),SUCCESS" >> "${{ needs.initialize.outputs.local_log_dir }}/timing.csv"

  # ==========================================================================
  # PHASE 2: 2 NODE SIMULATIONS
  # ==========================================================================
  node-simulation-1:
    name: Node Simulation 1/2
    needs: [initialize, health-check-1, health-check-2, health-check-3, health-check-4, health-check-5, health-check-6]
    runs-on: self-hosted
    steps:
      - name: Run Node Failure Simulation 1
        run: |
          START=$(date +%s)
          STABILIZATION=${{ github.event.inputs.stabilization_time_node || '60' }}
          WORKERS=("worker-w001" "worker-w002" "worker-w003" "worker-w004" "worker-w005" "worker-w006")
          TARGET=${WORKERS[$RANDOM % ${#WORKERS[@]}]}
          
          echo "Node Simulation 1: Target ${TARGET}"
          kubectl cordon ${TARGET}
          kubectl taint nodes ${TARGET} node.kubernetes.io/out-of-service=nodeshutdown:NoExecute --overwrite
          sleep ${STABILIZATION}
          kubectl uncordon ${TARGET}
          kubectl taint nodes ${TARGET} node.kubernetes.io/out-of-service- || true
          
          END=$(date +%s)
          echo "NODE_SIMULATION_1,${START},${END},$((END-START)),SUCCESS" >> "${{ needs.initialize.outputs.local_log_dir }}/timing.csv"

  node-simulation-2:
    name: Node Simulation 2/2
    needs: [initialize, node-simulation-1]
    runs-on: self-hosted
    steps:
      - name: Run Node Failure Simulation 2
        run: |
          START=$(date +%s)
          STABILIZATION=${{ github.event.inputs.stabilization_time_node || '60' }}
          WORKERS=("worker-w001" "worker-w002" "worker-w003" "worker-w004" "worker-w005" "worker-w006")
          TARGET=${WORKERS[$RANDOM % ${#WORKERS[@]}]}
          
          echo "Node Simulation 2: Target ${TARGET}"
          kubectl cordon ${TARGET}
          kubectl taint nodes ${TARGET} node.kubernetes.io/out-of-service=nodeshutdown:NoExecute --overwrite
          sleep ${STABILIZATION}
          kubectl uncordon ${TARGET}
          kubectl taint nodes ${TARGET} node.kubernetes.io/out-of-service- || true
          
          END=$(date +%s)
          echo "NODE_SIMULATION_2,${START},${END},$((END-START)),SUCCESS" >> "${{ needs.initialize.outputs.local_log_dir }}/timing.csv"

  # ==========================================================================
  # PHASE 3: 2 INTERIM HEALTH CHECKS
  # ==========================================================================
  interim-health-check-1:
    name: Interim Health Check 1/2
    needs: [initialize, node-simulation-2]
    runs-on: self-hosted
    steps:
      - name: Run Interim Health Check 1
        run: |
          START=$(date +%s)
          kubectl get nodes -o wide
          END=$(date +%s)
          echo "INTERIM_HEALTH_CHECK_1,${START},${END},$((END-START)),SUCCESS" >> "${{ needs.initialize.outputs.local_log_dir }}/timing.csv"

  interim-health-check-2:
    name: Interim Health Check 2/2
    needs: [initialize, interim-health-check-1]
    runs-on: self-hosted
    steps:
      - name: Run Interim Health Check 2
        run: |
          START=$(date +%s)
          kubectl get nodes -o wide
          END=$(date +%s)
          echo "INTERIM_HEALTH_CHECK_2,${START},${END},$((END-START)),SUCCESS" >> "${{ needs.initialize.outputs.local_log_dir }}/timing.csv"

  # ==========================================================================
  # PHASE 4: 2 RACK SIMULATIONS
  # ==========================================================================
  rack-simulation-1:
    name: Rack Simulation 1/2
    needs: [initialize, interim-health-check-2]
    runs-on: self-hosted
    steps:
      - name: Run Rack Failure Simulation 1
        run: |
          START=$(date +%s)
          STABILIZATION=${{ github.event.inputs.stabilization_time_rack || '60' }}
          
          declare -A ZONE_NODES
          ZONE_NODES["R1"]="master-m001 worker-w001 worker-w002"
          ZONE_NODES["R2"]="master-m002 worker-w003 worker-w004"
          ZONE_NODES["R3"]="master-m003 worker-w005 worker-w006"
          
          ZONES=("R1" "R2")
          TARGET_ZONE=${ZONES[$RANDOM % ${#ZONES[@]}]}
          TARGET_NODES="${ZONE_NODES[$TARGET_ZONE]}"
          
          echo "Rack Simulation 1: Zone ${TARGET_ZONE}"
          for node in ${TARGET_NODES}; do
            kubectl cordon ${node}
            kubectl taint nodes ${node} node.kubernetes.io/out-of-service=zonefailure:NoExecute --overwrite
          done
          
          sleep 30
          
          for node in ${TARGET_NODES}; do
            kubectl uncordon ${node}
            kubectl taint nodes ${node} node.kubernetes.io/out-of-service- || true
          done
          
          sleep ${STABILIZATION}
          
          END=$(date +%s)
          echo "RACK_SIMULATION_1,${START},${END},$((END-START)),SUCCESS" >> "${{ needs.initialize.outputs.local_log_dir }}/timing.csv"

  rack-simulation-2:
    name: Rack Simulation 2/2
    needs: [initialize, rack-simulation-1]
    runs-on: self-hosted
    steps:
      - name: Run Rack Failure Simulation 2
        run: |
          START=$(date +%s)
          STABILIZATION=${{ github.event.inputs.stabilization_time_rack || '60' }}
          
          declare -A ZONE_NODES
          ZONE_NODES["R1"]="master-m001 worker-w001 worker-w002"
          ZONE_NODES["R2"]="master-m002 worker-w003 worker-w004"
          ZONE_NODES["R3"]="master-m003 worker-w005 worker-w006"
          
          ZONES=("R1" "R2")
          TARGET_ZONE=${ZONES[$RANDOM % ${#ZONES[@]}]}
          TARGET_NODES="${ZONE_NODES[$TARGET_ZONE]}"
          
          echo "Rack Simulation 2: Zone ${TARGET_ZONE}"
          for node in ${TARGET_NODES}; do
            kubectl cordon ${node}
            kubectl taint nodes ${node} node.kubernetes.io/out-of-service=zonefailure:NoExecute --overwrite
          done
          
          sleep 30
          
          for node in ${TARGET_NODES}; do
            kubectl uncordon ${node}
            kubectl taint nodes ${node} node.kubernetes.io/out-of-service- || true
          done
          
          sleep ${STABILIZATION}
          
          END=$(date +%s)
          echo "RACK_SIMULATION_2,${START},${END},$((END-START)),SUCCESS" >> "${{ needs.initialize.outputs.local_log_dir }}/timing.csv"

  # ==========================================================================
  # PHASE 5: 2 FINAL HEALTH CHECKS
  # ==========================================================================
  final-health-check-1:
    name: Final Health Check 1/2
    needs: [initialize, rack-simulation-2]
    runs-on: self-hosted
    steps:
      - name: Run Final Health Check 1
        run: |
          START=$(date +%s)
          kubectl get nodes -o wide
          END=$(date +%s)
          echo "FINAL_HEALTH_CHECK_1,${START},${END},$((END-START)),SUCCESS" >> "${{ needs.initialize.outputs.local_log_dir }}/timing.csv"

  final-health-check-2:
    name: Final Health Check 2/2
    needs: [initialize, final-health-check-1]
    runs-on: self-hosted
    steps:
      - name: Run Final Health Check 2
        run: |
          START=$(date +%s)
          kubectl get nodes -o wide
          END=$(date +%s)
          echo "FINAL_HEALTH_CHECK_2,${START},${END},$((END-START)),SUCCESS" >> "${{ needs.initialize.outputs.local_log_dir }}/timing.csv"

  # ==========================================================================
  # FINALIZE
  # ==========================================================================
  finalize:
    name: Finalize Scaled Workflow
    needs: [initialize, final-health-check-2]
    runs-on: self-hosted
    if: always()
    steps:
      - name: Generate Summary
        run: |
          LOG_DIR="${{ needs.initialize.outputs.local_log_dir }}"
          RUN_ID="${{ needs.initialize.outputs.run_id }}"
          
          cat > "${LOG_DIR}/metrics.txt" << EOF
          # Scaled (2x) GitHub Actions Metrics
          # Generated: $(date)
          
          PLATFORM=GitHub_Actions_Scaled
          SCALE=2x
          RUN_ID=${RUN_ID}
          STATUS=SUCCESS
          EOF
          
          echo "================================================================"
          echo "SCALED (2x) GITHUB ACTIONS COMPLETE"
          echo "================================================================"
          echo "Run ID: ${RUN_ID}"
          cat "${LOG_DIR}/timing.csv" 2>/dev/null || echo "No timing data"

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: scaled-logs-${{ needs.initialize.outputs.run_id }}
          path: ${{ needs.initialize.outputs.local_log_dir }}
