######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : test-workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : clean_up_local_level_3_0.sub
######################################################################
stream_error  = false
stream_output = false
environment = "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=0682ef7f-50db-48e0-bc4f-d15064e6ac0b PEGASUS_WF_LABEL=test-workflow PEGASUS_DAG_JOB_ID=clean_up_local_level_3_0 PEGASUS_SITE=local PEGASUS_BIN_DIR=/usr/bin _PEGASUS_CONNECT_STDIN=true"
arguments = "pegasus-kickstart  -n pegasus::cleanup -N null -i - -R local  -L test-workflow -T 2026-01-26T16:48:57+05:30 pegasus-transfer "
error = /app/output/submit/root/pegasus/test-workflow/run0001//00/00/clean_up_local_level_3_0.err
executable = /usr/share/pegasus/sh/pegasus-lite-local.sh
input = /app/output/submit/root/pegasus/test-workflow/run0001//00/00/clean_up_local_level_3_0.in
log = /app/output/submit/root/pegasus/test-workflow/run0001/test-workflow-0.log
notification = NEVER
output = /app/output/submit/root/pegasus/test-workflow/run0001//00/00/clean_up_local_level_3_0.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 1000
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "0682ef7f-50db-48e0-bc4f-d15064e6ac0b"
+pegasus_wf_uuid = "0682ef7f-50db-48e0-bc4f-d15064e6ac0b"
+pegasus_version = "5.0.9"
+pegasus_wf_name = "test-workflow-0"
+pegasus_wf_time = "20260126T164857+0530"
+pegasus_wf_xformation = "pegasus::cleanup"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "clean_up_local_level_3_0"
+pegasus_job_class = 8
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_gpus = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
