######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : test-workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : health-check_ID0000001.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=0682ef7f-50db-48e0-bc4f-d15064e6ac0b PEGASUS_WF_LABEL=test-workflow PEGASUS_DAG_JOB_ID=health-check_ID0000001 PEGASUS_SITE=local _PEGASUS_INITIAL_DIR=/app/scratch/root/pegasus/test-workflow/run0001 _PEGASUS_TRANSFER_INPUT_FILES=/app/output/submit/root/pegasus/test-workflow/run0001/pegasus-worker-5.0.9-x86_64_ubuntu_20.tar.gz,/app/output/submit/root/pegasus/test-workflow/run0001/pegasus-lite-common.sh, _PEGASUS_TRANSFER_OUTPUT_FILES=out1.txt, PEGASUS_BIN_DIR=/usr/bin"
arguments = "/app/output/submit/root/pegasus/test-workflow/run0001/00/00/health-check_ID0000001.sh "
error = /app/output/submit/root/pegasus/test-workflow/run0001//00/00/health-check_ID0000001.err
executable = /usr/share/pegasus/sh/pegasus-lite-local.sh
initialdir = /app/scratch/root/pegasus/test-workflow/run0001
log = /app/output/submit/root/pegasus/test-workflow/run0001/test-workflow-0.log
notification = NEVER
output = /app/output/submit/root/pegasus/test-workflow/run0001//00/00/health-check_ID0000001.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 10
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "0682ef7f-50db-48e0-bc4f-d15064e6ac0b"
+pegasus_wf_uuid = "0682ef7f-50db-48e0-bc4f-d15064e6ac0b"
+pegasus_version = "5.0.9"
+pegasus_wf_name = "test-workflow-0"
+pegasus_wf_time = "20260126T164857+0530"
+pegasus_wf_xformation = "rack::health-check:1.0"
+pegasus_wf_dax_job_id = "ID0000001"
+pegasus_wf_dag_job_id = "health-check_ID0000001"
+pegasus_job_class = 1
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_gpus = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
