######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : rack-resiliency-1x-20260122-134419, Index = 0, Count = null
# SUBMIT FILE NAME : create_dir_rack-resiliency-1x-20260122-134419_0_local.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 KUBECONFIG=/home/snu/kubernetes/kubeconfig-master PATH=/home/snu/pegasus-venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=3a6553b9-f31e-40d7-855c-2d5e8c2e960e PEGASUS_WF_LABEL=rack-resiliency-1x-20260122-134419 PEGASUS_DAG_JOB_ID=create_dir_rack-resiliency-1x-20260122-134419_0_local PEGASUS_SITE=local PEGASUS_BIN_DIR=/usr/bin _PEGASUS_CONNECT_STDIN=true"
arguments = "pegasus-kickstart  -n pegasus::dirmanager -N null -i - -R local  -L rack-resiliency-1x-20260122-134419 -T 2026-01-22T13:44:19+05:30 pegasus-transfer "
error = /home/snu/kubernetes/comparison-logs/pegasus-1x/pegasus-1x-20260122-134419-1/submit/snu/pegasus/rack-resiliency-1x-20260122-134419/run0001//00/00/create_dir_rack-resiliency-1x-20260122-134419_0_local.err
executable = /usr/share/pegasus/sh/pegasus-lite-local.sh
input = /home/snu/kubernetes/comparison-logs/pegasus-1x/pegasus-1x-20260122-134419-1/submit/snu/pegasus/rack-resiliency-1x-20260122-134419/run0001//00/00/create_dir_rack-resiliency-1x-20260122-134419_0_local.in
log = /home/snu/kubernetes/comparison-logs/pegasus-1x/pegasus-1x-20260122-134419-1/submit/snu/pegasus/rack-resiliency-1x-20260122-134419/run0001/rack-resiliency-1x-20260122-134419-0.log
notification = NEVER
output = /home/snu/kubernetes/comparison-logs/pegasus-1x/pegasus-1x-20260122-134419-1/submit/snu/pegasus/rack-resiliency-1x-20260122-134419/run0001//00/00/create_dir_rack-resiliency-1x-20260122-134419_0_local.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 800
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "3a6553b9-f31e-40d7-855c-2d5e8c2e960e"
+pegasus_wf_uuid = "3a6553b9-f31e-40d7-855c-2d5e8c2e960e"
+pegasus_version = "5.0.9"
+pegasus_wf_name = "rack-resiliency-1x-20260122-134419-0"
+pegasus_wf_time = "20260122T134419+0530"
+pegasus_wf_xformation = "pegasus::dirmanager"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "create_dir_rack-resiliency-1x-20260122-134419_0_local"
+pegasus_job_class = 6
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_gpus = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
