apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: resilience-heft-
  namespace: argo
  labels:
    app: resilience-simulation
    scheduler: heft
spec:
  entrypoint: heft-resilience-dag
  serviceAccountName: argo-workflow
  
  # HEFT Parameters
  arguments:
    parameters:
    - name: stabilization-time
      value: "60"

  # Volume for logs
  volumes:
  - name: logs-volume
    hostPath:
      path: /home/vagrant/heft-argo-logs
      type: DirectoryOrCreate
  
  templates:
  # ==========================================================================
  # MAIN DAG - HEFT-Optimized Resilience Simulation
  # ==========================================================================
  - name: heft-resilience-dag
    dag:
      tasks:
      # Step 0: HEFT Initialization - Compute optimal schedule
      - name: heft-init
        template: heft-initialize
        
      # Step 1: Parallel Health Checks
      - name: health-check-1
        template: health-check
        dependencies: [heft-init]
        arguments:
          parameters:
          - name: check-id
            value: "1"
            
      - name: health-check-2
        template: health-check
        dependencies: [heft-init]
        arguments:
          parameters:
          - name: check-id
            value: "2"
            
      - name: health-check-3
        template: health-check
        dependencies: [heft-init]
        arguments:
          parameters:
          - name: check-id
            value: "3"
      
      # Step 2: Node Failure Simulation with HEFT exclusion
      - name: node-simulation
        template: node-failure-sim
        dependencies: [health-check-1, health-check-2, health-check-3]
        arguments:
          parameters:
          - name: exclude-node
            value: "{{tasks.heft-init.outputs.parameters.heft-exclude-node}}"
          - name: exclude-zone
            value: "{{tasks.heft-init.outputs.parameters.heft-exclude-zone}}"
      
      # Step 3: Interim Health Check
      - name: interim-health-check
        template: health-check
        dependencies: [node-simulation]
        arguments:
          parameters:
          - name: check-id
            value: "interim"
      
      # Step 4: Rack Failure Simulation with HEFT zone exclusion
      - name: rack-simulation
        template: rack-failure-sim
        dependencies: [interim-health-check]
        arguments:
          parameters:
          - name: exclude-node
            value: "{{tasks.heft-init.outputs.parameters.heft-exclude-node}}"
          - name: exclude-zone
            value: "{{tasks.heft-init.outputs.parameters.heft-exclude-zone}}"
      
      # Step 5: Final Health Check
      - name: final-health-check
        template: health-check
        dependencies: [rack-simulation]
        arguments:
          parameters:
          - name: check-id
            value: "final"
      
      # Step 6: Finalize
      - name: finalize
        template: finalize-metrics
        dependencies: [final-health-check]

  # ==========================================================================
  # HEFT INITIALIZATION TEMPLATE
  # ==========================================================================
  - name: heft-initialize
    nodeSelector:
      kubernetes.io/hostname: master-m003
    outputs:
      parameters:
      - name: heft-exclude-node
        valueFrom:
          path: /tmp/heft-exclude-node
      - name: heft-exclude-zone
        valueFrom:
          path: /tmp/heft-exclude-zone
    container:
      image: python:3.9-slim
      command: ["/bin/bash", "-c"]
      args:
      - |
        echo "================================================"
        echo "HEFT SCHEDULER INITIALIZATION"
        echo "================================================"
        
        # HEFT scheduling decision:
        # We run on master-m003 (zone R3)
        # To prevent conflict, exclude R3 nodes from failure simulation
        
        EXECUTION_NODE="master-m003"
        EXECUTION_ZONE="R3"
        
        # Exclude a worker from the execution zone
        EXCLUDE_NODE="worker-w005"  # R3 worker node
        EXCLUDE_ZONE="R3"
        
        echo "HEFT Decision:"
        echo "  Execution Node: ${EXECUTION_NODE}"
        echo "  Execution Zone: ${EXECUTION_ZONE}"
        echo "  Exclude Node from simulation: ${EXCLUDE_NODE}"
        echo "  Exclude Zone from rack sim: ${EXCLUDE_ZONE}"
        
        # Write outputs for other steps
        echo -n "${EXCLUDE_NODE}" > /tmp/heft-exclude-node
        echo -n "${EXCLUDE_ZONE}" > /tmp/heft-exclude-zone
        
        echo "HEFT initialization complete"

  # ==========================================================================
  # HEALTH CHECK TEMPLATE
  # ==========================================================================
  - name: health-check
    inputs:
      parameters:
      - name: check-id
    nodeSelector:
      kubernetes.io/hostname: master-m003
    container:
      image: kushsahni1/chaos-sim:latest
      command: ["python3", "/app/rack_resiliency_to_host.py", "health-check"]
      args:
      - "--stabilization-time=10"
      env:
      - name: CHECK_ID
        value: "{{inputs.parameters.check-id}}"
      - name: HEFT_ENABLED
        value: "true"
      volumeMounts:
      - name: logs-volume
        mountPath: /app/logs

  # ==========================================================================
  # NODE FAILURE SIMULATION TEMPLATE (HEFT-aware)
  # ==========================================================================
  - name: node-failure-sim
    inputs:
      parameters:
      - name: exclude-node
      - name: exclude-zone
    nodeSelector:
      kubernetes.io/hostname: master-m003
    container:
      image: kushsahni1/chaos-sim:latest
      command: ["python3", "/app/rack_resiliency_to_host.py", "simulate-node"]
      args:
      - "--stabilization-time={{workflow.parameters.stabilization-time}}"
      env:
      - name: HEFT_ENABLED
        value: "true"
      - name: HEFT_EXCLUDE_NODE
        value: "{{inputs.parameters.exclude-node}}"
      - name: HEFT_EXCLUDE_ZONE
        value: "{{inputs.parameters.exclude-zone}}"
      volumeMounts:
      - name: logs-volume
        mountPath: /app/logs

  # ==========================================================================
  # RACK FAILURE SIMULATION TEMPLATE (HEFT-aware)
  # ==========================================================================
  - name: rack-failure-sim
    inputs:
      parameters:
      - name: exclude-node
      - name: exclude-zone
    nodeSelector:
      kubernetes.io/hostname: master-m003
    container:
      image: kushsahni1/chaos-sim:latest
      command: ["python3", "/app/rack_resiliency_to_host.py", "simulate-rack"]
      args:
      - "--stabilization-time={{workflow.parameters.stabilization-time}}"
      env:
      - name: HEFT_ENABLED
        value: "true"
      - name: HEFT_EXCLUDE_NODE
        value: "{{inputs.parameters.exclude-node}}"
      - name: HEFT_EXCLUDE_ZONE
        value: "{{inputs.parameters.exclude-zone}}"
      volumeMounts:
      - name: logs-volume
        mountPath: /app/logs

  # ==========================================================================
  # FINALIZE METRICS TEMPLATE
  # ==========================================================================
  - name: finalize-metrics
    nodeSelector:
      kubernetes.io/hostname: master-m003
    container:
      image: python:3.9-slim
      command: ["/bin/bash", "-c"]
      args:
      - |
        echo "============================================"
        echo "HEFT-OPTIMIZED RESILIENCE SIMULATION COMPLETE"
        echo "============================================"
        echo "Workflow: resilience-heft"
        echo "Scheduler: HEFT"
        echo "Logs: /home/vagrant/heft-argo-logs"
        ls -la /app/logs/ 2>/dev/null || echo "Logs directory accessed"
        echo "HEFT simulation completed successfully"
      volumeMounts:
      - name: logs-volume
        mountPath: /app/logs
