######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : montage-1.0deg-20260202-151957, Index = 0, Count = null
# SUBMIT FILE NAME : mBgExec_ID0000011.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=c45f3520-52b5-4c20-abee-69c6a90ec30b PEGASUS_WF_LABEL=montage-1.0deg-20260202-151957 PEGASUS_DAG_JOB_ID=mBgExec_ID0000011 PEGASUS_SITE=local _PEGASUS_TRANSFER_INPUT_FILES=/app/output/test/submit/root/pegasus/montage-1.0deg-20260202-151957/run0001/pegasus-worker-5.0.9-x86_64_ubuntu_20.tar.gz,/app/output/test/submit/root/pegasus/montage-1.0deg-20260202-151957/run0001/00/00/mBgModel_ID0000010.meta,/app/output/test/submit/root/pegasus/montage-1.0deg-20260202-151957/run0001/00/00/mProjectPP_ID0000001.meta,/app/output/test/submit/root/pegasus/montage-1.0deg-20260202-151957/run0001/pegasus-lite-common.sh, PEGASUS_BIN_DIR=/usr/bin"
arguments = "/app/output/test/submit/root/pegasus/montage-1.0deg-20260202-151957/run0001/00/00/mBgExec_ID0000011.sh "
error = /app/output/test/submit/root/pegasus/montage-1.0deg-20260202-151957/run0001//00/00/mBgExec_ID0000011.err
executable = /usr/share/pegasus/sh/pegasus-lite-local.sh
log = /app/output/test/submit/root/pegasus/montage-1.0deg-20260202-151957/run0001/montage-1.0deg-20260202-151957-0.log
notification = NEVER
output = /app/output/test/submit/root/pegasus/montage-1.0deg-20260202-151957/run0001//00/00/mBgExec_ID0000011.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 70
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "c45f3520-52b5-4c20-abee-69c6a90ec30b"
+pegasus_wf_uuid = "c45f3520-52b5-4c20-abee-69c6a90ec30b"
+pegasus_version = "5.0.9"
+pegasus_wf_name = "montage-1.0deg-20260202-151957-0"
+pegasus_wf_time = "20260202T152056+0530"
+pegasus_wf_xformation = "montage::mBgExec:6.0"
+pegasus_wf_dax_job_id = "ID0000011"
+pegasus_wf_dag_job_id = "mBgExec_ID0000011"
+pegasus_job_class = 1
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_gpus = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
